from __future__ import annotations

from collections.abc import Iterable

from fnmatch import fnmatchcase

import attrs
from attrs import field

from preempt.config.target_layers import TargetLayerConfig, TargetLayerSearchParams


@attrs.define(frozen=True, kw_only=True)
class LayerCandidate:
    layer_path: str = field()
    layer_class: str = field()
    layer_idx: int | None = field(default=None)


def layer_is_match(
    candidate: LayerCandidate,
    search_params: TargetLayerSearchParams,
) -> bool:
    return (
        (
            search_params.layer_class is None
            or candidate.layer_class == search_params.layer_class
        )
        and (
            search_params.layer_path_glob is None
            or fnmatchcase(candidate.layer_path, search_params.layer_path_glob)
        )
        and (
            search_params.layer_idx is None
            or candidate.layer_idx == search_params.layer_idx
        )
    )


def match_target_layers(
    candidates: Iterable[LayerCandidate],
    search_params: TargetLayerSearchParams,
) -> tuple[LayerCandidate, ...]:
    matches = tuple(
        filter(lambda layer: layer_is_match(layer, search_params), candidates)
    )
    if not matches:
        raise ValueError(
            "Could not find any layers matching the provided search parameters: "
            f"{search_params!r}"
        )
    if search_params.count is not None and len(matches) != search_params.count:
        raise ValueError(
            f"Found unexpected number of matching layers. Expected count: "
            f"{search_params.count}, Matches: {len(matches)}"
        )

    return matches


def resolve_target_layers(
    candidates: Iterable[LayerCandidate],
    config: TargetLayerConfig,
) -> dict[str, tuple[LayerCandidate, ...]]:
    candidates = tuple(candidates)

    return {
        spec.name: match_target_layers(candidates, spec.search_params)
        for spec in config.target_layers
    }


# TODO rework this, generated by kimi k3
def ensure_no_target_layer_overlap(
    resolved: dict[str, tuple[LayerCandidate, ...]],
) -> None:
    owners: dict[LayerCandidate, str] = {}

    for target_name, layers in resolved.items():
        for layer in layers:
            previous_name = owners.setdefault(layer, target_name)

            if previous_name != target_name:
                raise ValueError(
                    f"Layer {layer.layer_path!r} matches both "
                    f"{previous_name!r} and {target_name!r}."
                )
