version = 1
resolve_relative_paths = true

[llm]
model_id = "lmstudio-community/Qwen3.5-397B-A17B-MLX-8bit"
backend = "mlx_metal"
architecture = "qwen3-next"

[generation_settings]
max_tokens = 4096
prefill_chunk_size = 512


[stream_settings]
expert_bank_path = "../../expert-bank/qwen3.5-397b-8bit"
memory_budget_gb = 16
bypass_page_cache = true

[trace_settings]
output_path = "../../traces/qwen3.5-397b-8bit.parquet"
overwrite_output = true

[[trace_settings.target_layers]]
name = "Qwen3.5-397B-8bit-MoE-router"

[trace_settings.target_layers.search_params]
layer_class = "Qwen3NextSparseMoeBlock"
count = 60
