version = 1

[llm]
model_id = "unsloth/Qwen3.6-35B-A3B-UD-MLX-4bit"
backend = "mlx_metal"
architecture = "qwen3-next"

[generation_settings]
max_tokens = 1028
prefill_chunk_size = 512

# Currently, this has to be commented out to disable disk reads
[stream_settings]
expert_bank_path = "../expert-bank/qwen3.5-35b"
memory_bytes_budget = 4_000_000_000
bypass_page_cache = true

[trace_settings]
output_path = "../traces/router-events.parquet" # relative to this file, NOT cwd
overwrite_output = true

[[trace_settings.target_layers]]
name = "Qwen3.6-35B-expert-router"

[trace_settings.target_layers.search_params]
layer_class = "Qwen3NextSparseMoeBlock"
count = 40
